services:
  ldap-account-manager:
    build:
      context: .
    image: ldapaccountmanager/lam:latest
    container_name: lamstis
    restart: unless-stopped
    ports:
      - "8181:80"
      - "9443:443"
    volumes:
      - lametc/:/etc/ldap-account-manager
      - lamconfig/:/var/lib/ldap-account-manager/config
      - lamsession/:/var/lib/ldap-account-manager/sess
    environment:
      - LAM_PASSWORD=lam
      - LAM_LANG=en_US
      - LDAP_DOMAIN=kuncimasuk.com
      - LDAP_BASE_DN=dc=kuncimasuk,dc=com
      - LDAP_ADMIN_PASSWORD=ldapserver
      - ADMIN_USER=cn=admin,dc=kuncimasuk,dc=com
      - DEBUG=true
    hostname: ldap-account-manager
    depends_on:
      - openldap
    networks:
      - openldap
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    restart: unless-stopped
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=ldapstis
      - LDAP_DOMAIN=kuncimasuk.com
      - LDAP_BASE_DN=dc=kuncimasuk,dc=com
      - LDAP_ADMIN_PASSWORD=ldapserver
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=readonlyuser
      - LDAP_GROUPS_DN=ou=group,dc=kuncimasuk,dc=com
      - LDAP_USERS_DN=ou=people,dc=kuncimasuk,dc=com
      - LDAP_TLS_CRT_FILENAME: cert.pem
      - LDAP_TLS_KEY_FILENAME: privkey.pem
      - LDAP_TLS_CA_CRT_FILENAME: chain.pem
      - LDAP_TLS_VERIFY_CLIENT=never

    command: "--loglevel info --copy-service"
    volumes:
      - ldap:/var/lib/ldap
      - slapd:/etc/ldap/slapd.d
      - ./letsencrypt/live/kuncimasuk.com:/container/service/slapd/assets/certs
    hostname: ldap
    networks:
      - openldap

volumes:
  lametc:
  lamconfig:
  lamsession:
  ldap:
  slapd:
networks:
  openldap:
    driver: bridge
